[package]
name = "new_lib"
version = "0.1.0"
authors = ["dafer <fernando.cubides@merlinjobs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
new_binary = {path = "../new_binary"}